
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'programDIVIDE ID LPAREN MINUS NUMBER PLUS PRINT RPAREN SEMI TIMESprogram : statement_liststatement_list : statement_list statement\n| statementstatement : print_statement\n| expression_statementprint_statement : PRINT LPAREN expression RPAREN SEMIexpression_statement : expression SEMIexpression : expression PLUS expression\n| expression MINUS expression\n| expression TIMES expression\n| expression DIVIDE expressionexpression : LPAREN expression RPARENexpression : NUMBER'
    
_lr_action_items = {'PRINT':([0,2,3,4,5,10,13,25,],[6,6,-3,-4,-5,-2,-7,-6,]),'LPAREN':([0,2,3,4,5,6,7,10,11,13,14,15,16,17,25,],[7,7,-3,-4,-5,11,7,-2,7,-7,7,7,7,7,-6,]),'NUMBER':([0,2,3,4,5,7,10,11,13,14,15,16,17,25,],[9,9,-3,-4,-5,9,-2,9,-7,9,9,9,9,-6,]),'$end':([1,2,3,4,5,10,13,25,],[0,-1,-3,-4,-5,-2,-7,-6,]),'SEMI':([8,9,19,20,21,22,23,24,],[13,-13,-12,-8,-9,-10,-11,25,]),'PLUS':([8,9,12,18,19,20,21,22,23,],[14,-13,14,14,-12,14,14,14,14,]),'MINUS':([8,9,12,18,19,20,21,22,23,],[15,-13,15,15,-12,15,15,15,15,]),'TIMES':([8,9,12,18,19,20,21,22,23,],[16,-13,16,16,-12,16,16,16,16,]),'DIVIDE':([8,9,12,18,19,20,21,22,23,],[17,-13,17,17,-12,17,17,17,17,]),'RPAREN':([9,12,18,19,20,21,22,23,],[-13,19,24,-12,-8,-9,-10,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement_list':([0,],[2,]),'statement':([0,2,],[3,10,]),'print_statement':([0,2,],[4,4,]),'expression_statement':([0,2,],[5,5,]),'expression':([0,2,7,11,14,15,16,17,],[8,8,12,18,20,21,22,23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement_list','program',1,'p_program','parser.py',7),
  ('statement_list -> statement_list statement','statement_list',2,'p_statement_list','parser.py',11),
  ('statement_list -> statement','statement_list',1,'p_statement_list','parser.py',12),
  ('statement -> print_statement','statement',1,'p_statement','parser.py',19),
  ('statement -> expression_statement','statement',1,'p_statement','parser.py',20),
  ('print_statement -> PRINT LPAREN expression RPAREN SEMI','print_statement',5,'p_print_statement','parser.py',24),
  ('expression_statement -> expression SEMI','expression_statement',2,'p_expression_statement','parser.py',28),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','parser.py',33),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','parser.py',34),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','parser.py',35),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','parser.py',36),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','parser.py',40),
  ('expression -> NUMBER','expression',1,'p_expression_number','parser.py',44),
]
